examples/react/file-upload/README.md, examples/react/multi-file-upload/README.md, examples/react/sign-up-in/README.md
This just adds a couple lines to the example READMEs to make sure people build the main `w3ui` packages before running the examples.  Don't know if there's an issue for it, but closes @jchris's slack ping :smile:
=> chore: add note to example readmes about building main package

README.md, examples/README.md, examples/react/README.md, examples/solid/README.md, examples/vue/README.md
This just copies the example "index" from the main README to `examples/README.md` and the framework-specific example dirs.
This is mostly so we have something to link to from the "getting started resources" blog post I'm working on. 
@alanshaw LMK if you think the framework-specific ones add too much maintenance overhead... I don't love that I just added a bunch of places to update as things change. I think we can get away with just linking to `examples/README.md` from the blog post instead, but it feels nice as a viewer to have a bit of context when browsing the subdirs on github.
=> chore: add readmes to example folders with overview

examples/vanilla/file-upload/src/upload.js, examples/vanilla/multi-file-upload/src/upload.js, package-lock.json, packages/keyring-core/package.json, packages/keyring-core/src/index.ts, packages/react-uploader/src/providers/Uploader.tsx, packages/solid-uploader/src/providers/Uploader.ts, packages/uploader-core/package.json, packages/uploader-core/src/index.ts, packages/uploads-list-core/package.json, packages/uploads-list-core/src/index.ts, packages/vue-uploader/src/providers/Uploader.ts
This PR fixes the uploads listing by calling the `upload/list` capability.
After a chunked upload is complete, the uploader now calls `upload/add` to register an "upload" and associate multiple CAR files together.
`upload/list` capability will list out the uploads registered using the `upload/add` call.
There's no breaking API changes but existing uploads will no longer be displayed in the list since they were not registered using `upload/add`.
supersedes https://github.com/web3-storage/w3ui/pull/103
=> fix: uploads listing

examples/react/ui/src/ContentPage.js, packages/react-ui/src/SimpleUploader.tsx, packages/react-ui/src/index.ts, packages/react-uploader/src/Uploader.tsx, packages/react-uploader/src/index.ts
I think it makes more sense to include these "headless UI" style components in the @w3ui/react-* packages rather than bundling them together in the react-ui package. It feels more intuitive given the naming - if we do want to have the "no UI" style components in a separate package I'd advocate for callling that package `react-uploader-provider` or `react-uploader-api` or something, but given how much code this is and the fact that tree shaking is pretty good, it seems ok to me to bundle them together.
the react-ui package will be reserved for higher level "customizable UI" style components and can now have opinions about the right way to do customization at the top level rather than having two different flavors of customizability in a single package.
@alanshaw @cmunns curious what you …
=> chore: move Uploader into react-uploader package

packages/react-ui/src/SimpleUploader.tsx, packages/react-ui/src/SimpleUploadsList.tsx, packages/react-uploader/src/Uploader.tsx, packages/react-uploads-list/src/UploadsList.tsx, packages/react-uploads-list/src/index.ts
first pass at UploadsLists headless components. needs an example in react-ui to prove out
two main questions for reviewers:
1) any thoughts on the API for this component? feel free to pass on evaluating this until I have an example/docs
2) is it worth adding a "prev" function to the UploaderProvider so that we could build out a real basic "paging" component? I don't think we'll be able to add current page/total number of pages controls and indicators without more support from the backend service, but just forward and backward is better than a one way street
3) otoh, should I maybe add an infinite scroll list component to show off what we can do with the current API?
TODO:
=> feat: UploadsList components

packages/react-keyring/src/Authenticator.tsx, packages/react-keyring/src/index.ts, packages/react-ui/src/SimpleAuthenticator.tsx, packages/react-ui/src/index.ts
add "headless" Authenticator component and use it to build a "customizable" SimpleAuthenticator that works the way the Authenticator components in our examples work
separate PR against `feat/w3ui-ui` to make feedback easier - this component will replace the `Authenticator` components we've copied into a number of different examples
this is the last major React "customizable" UI component - if we're happy with this we should probably push forward with Vue and SolidJS versions of each of them - hopefully more straightforward now that the architecture/design work has been done
=> feat: Add Authenticator and SimpleAuthenticator

rollup.config.ts
This adds `.js` to the set of file extensions processed by babel.
I'm hoping that this will fix #160, since after running `npm run build` with this change I no longer see any class private members in `packages/react-keyring/build/esm/index.js`, which is where the example was failing before.
The downside of this change is that the rolled-up `index.js` grew from 198kb to 300kb for react-keyring. I assume the other modules are affected as well.
I also haven't been able to test this in codesandbox, since I don't know how to make it depend on an unreleased npm package (or if that's even possible).
=> fix: run babel on .js files as well as .ts

examples/react/uploads-list/src/App.js, examples/react/uploads-list/src/ContentPage.js, examples/react/uploads-list/src/components/Authenticator.js
one slightly weird thing about this is that I realized we need to manually call `next` to get the next page of results - not sure if that's intentional and we might want to add that to the `react-uploads-list` package for developer convenience
=> fix: update react uploads list example

examples/solid/uploads-list/src/ContentPage.jsx, packages/solid-keyring/package.json, packages/solid-keyring/src/providers/Keyring.ts, packages/solid-uploader/package.json, packages/solid-uploader/src/index.ts, packages/solid-uploads-list/src/resources/UploadsList.ts
vite is more particular about type imports and peer vs dev vs regular dependencies - these fixes all help make the solid examples work properly
frustratingly, something still seems off about the way vite is trying to load the umd build - these changes work on my pnpm branch but still fail here. code examples should be helpful for folks trying to build, but it may still be tricky to get these examples working until we move to pnpm
=> fix: get solid examples working again

docs/react-uploads-list.md
(this PR replaces https://github.com/web3-storage/w3ui/pull/151 which was against a now-obsolete branch)
At least in certain contexts (specifically I was viewing from the URL <https://github.com/web3-storage/w3ui/blob/w3ui/docs/react-uploads-list.md> via the `next` branch) the useKeyring documentation link led to a 404 when clicked. Adding the `.md` extension seems to be all that's needed.
=> Fix docs link from react-uploads-list to keyring page

examples/react/ui/src/ContentPage.jsx, packages/react-ui/src/SimpleUploader.tsx, packages/react-ui/src/styles/uploader.css
Use @cmunns's styles from #140 to enable css-variable-based customizable styling of SimpleUploader.
Demonstrate how this can be used with a default stylesheet we provide to get great looking components out of the box.
=> feat: use css variable-based styles to enable customization

examples/react/playground/.storybook/main.cjs, examples/react/playground/.storybook/preview-head.html, examples/react/playground/.storybook/preview.js, examples/react/playground/package.json, examples/react/playground/src/stories/Introduction.mdx, examples/react/playground/src/stories/Uploader.stories.tsx, examples/react/playground/src/stories/UploadsList.stories.tsx, pnpm-lock.yaml
Add storybook scaffolding so we can iterate on our components and all the states they can be in.
Uses the beta release of storybook v7 as it has support for pnpm.
Part of #225 - we need this to demonstrate out components in all their possible states so we can make them good.
License: MIT
=> feat: add storybook

examples/react/w3console/package.json, examples/react/w3console/src/app.tsx, examples/react/w3console/src/index.css, packages/react-uploader/src/Uploader.tsx, packages/react/src/Uploader.tsx, packages/react/src/UploadsList.tsx, packages/react/src/styles/uploader.css, pnpm-lock.yaml
first up: improved space creation flow
There are few different ways this could work, but the fact that we store `currentSpace` in the Agent combined with the fact that that `currentSpace` is updated automatically when we call `createSpace` makes it harder to implement some designs.
Put another way, it would be hard to have a space creator that does not change the currently selected space, so these changes lean into the way state management works right now.
https://user-images.githubusercontent.com/1113/213601254-86fd1114-e6d3-45a6-add3-44100166904a.mp4
=> fix: w3console polish

examples/react/w3console/src/index.css, packages/react/src/Uploader.tsx, packages/react/src/styles/uploader.css
refinements to the Upload component to
- make drag and drop work and fix the click area.
- make it look nice.
- add more namespacing of our css classes.
_there is still much todo. particularly around how we report progress which needs changes to the upload-client lib to get the methdods we need, but this moves us forwards._
License: MIT
=> feat: Improve upload component flow

packages/react-uploads-list/src/UploadsList.tsx, packages/react-uploads-list/src/providers/UploadsList.tsx
rather than doing this in the headless component, do it in the hook so that hook users also get a page of results. originally had this in the provider but that had timing issues and only worked sometimes.
=> fix: load first page of uploads list in provider

.codesandbox/ci.json, package.json
- codesansbox ci now support node 18
- disable `buildCommand` as it is done after install by the prepare lifecycle script
see: https://codesandbox.io/docs/learn/sandboxes/ci#configuration-format
fixes #237
note: there is an issue to consolidate the examples in #256 but our current set of examples are linked to from beta.ui.web3.storage so if we can get them working again without too much pain I think we should.
License: MIT
=> chore: get codesandbox examples working again

.github/workflows/examples.yaml, examples/test/playwright/README.md, package.json
by running pnpm exec playwright install from the playwright dir, pnpm knows to use the version of playwright that we depend on rather than the latest version.
without this change we end up installing the latest browesers and then the tests fail as they can't find the older versions that they assume will have been installed.
...and it turns out `pnpx` is deprecated, and we should be using `pnpm exec` anyway.
fixes: https://github.com/web3-storage/w3ui/issues/297
see: https://pnpm.io/6.x/cli/exec
License: MIT
=> fix: install correct browser versions for playwright tests

examples/react/w3console/package.json, examples/react/w3console/src/app.tsx, examples/react/w3console/src/share.tsx, packages/keyring-core/src/index.ts, packages/react-keyring/src/Authenticator.tsx, packages/react-keyring/src/providers/Keyring.tsx, packages/solid-keyring/src/providers/Keyring.ts, pnpm-lock.yaml
Allow user to delegate access to a space.
Adds createDelegation to keyring-core and chases it through {react,solid}-keyring
https://user-images.githubusercontent.com/58871/214885759-2bcf7167-7001-4ffd-b5f4-a0d4b51a9355.mov
To keep this PR reviewable, importing delegations will be added in a subsequent PR.
License: MIT
=> feat: delegate access to spaces

examples/react/w3console/src/app.tsx, packages/react/src/Authenticator.tsx, packages/react/src/styles/all.css
I broke the w3console styling by failing to include some of the new stylesheets from the react components. Fix that, and introduce an omnibus CSS file called `all.css` to make this easier in the future.
Also tweak the Authenticator component to accept a top-level CSS class - I didn't end up using this, but implemented it while debugging and I think it's good to leave in.
=> fix: fix w3console styling

.github/actions/pnpm/action.yml
Cutting a new release earlier today failed. Fortunately @alanshaw and @olizilla noticed that our working w3protocol builds have two extra lines of relevant config, one of which seems to be the culprit:
> @alanshaw
> Only difference I can see is with w3ui and w3protocol is that setup-node in w3protocol sets cache: pnpm and registry-url: 'https://registry.npmjs.org' https://github.com/web3-storage/w3protocol/blob/4d72ba3a1ce2564cda13c62137967613b18334a7/.github/workflows/release.yml#L47-L48 which is not being set here: https://github.com/web3-storage/w3ui/blob/0c661c6f4d28776b4ac7ad1aea3e0958186f8480/.github/actions/pnpm/action.yml#L7-L9
> olizilla
> it looks like registry-url must be set for setup-node to configure npm with an auth token: …
=> fix: add registry-url and cache config to github actions setup-node

packages/keyring-core/src/index.ts
Mainly doing this to get release-please to queue up a new keyring-core release after the previous one failed in a way that required updates to the build configs.
=> chore: document getCurrentSpace and getSpaces

packages/keyring-core/src/index.ts
`release-please` doesn't create a release for chores, so my last attempt to create a new keyring-core release failed.
Add some basic docs, and call this a `fix` to get `release-please` to do the right thing.
=> fix: add more docs

examples/react/w3console/index.html, examples/react/w3console/src/app.tsx, packages/react/src/Authenticator.tsx
only include the `w3ui-authenticator` class in the dom when we want to show the log in box.
otherwise the layout we choose for the register form is inherited by the logged in app layout which is undesirable
fixes https://github.com/web3-storage/w3ui/issues/351
License: MIT
=> fix: remove authenticator class when registed

examples/react/w3console/public/_headers
IDK why but cloudflare pages is not setting `Content-Type` header. This PR adds a [`_headers` file](https://developers.cloudflare.com/pages/platform/headers) that sets them for the file types we currently generate.
=> fix: add _headers

examples/react/w3console/src/components/SpaceCreator.tsx, packages/keyring-core/src/index.ts, packages/react-keyring/src/providers/Keyring.tsx, packages/react/src/SpaceCreator.tsx
Pass the value of the VITE_W3UP_PROVIDER env variable along to registerSpace. This lets us configure the provider used during space registration at the app level.
=> chore: pass VITE_W3UP_PROVIDER along to registerSpace

.release-please-manifest.json, release-please-config.json
I tried to merge more than one release-please PR at once and it really hated it, leaving 6 packages in a confusing state. I want to push them again, which afaict means setting version numbers in the config file temporarily.
I will remove these once the release is done.
=> fix: set version numbers for packages release-please fumbled

examples/react/w3console/src/components/SpaceCreator.tsx
because we weren't `await`ing here the space creation UI would flash empty again, which was very confusing
=> fix: wait for register space before returning from space create onSubmit

examples/react/w3console/src/components/Authenticator.tsx
the colors match the login box, so are less jarring, and the cancel button is hidden! it doesn't work yet! See next PR.
**after**
**before**
License: MIT
=> fix: w3console email check page improvements

.github/workflows/conventional-commits.yml
some tasty copypasta from https://github.com/web3-storage/w3protocol/blob/main/.github/workflows/conventional-commits.yml
=> chore: add workflow to make sure we use "conventional" commit messages

docs/keyring-core.md, docs/vue-keyring.md, examples/react/file-upload/src/components/Authenticator.jsx, examples/react/multi-file-upload/src/components/Authenticator.jsx, examples/react/playground/src/components/Authenticator.jsx, examples/react/sign-up-in/src/ContentPage.jsx, examples/react/uploads-list/src/components/Authenticator.jsx, examples/solid/file-upload/src/components/Authenticator.jsx, examples/solid/multi-file-upload/src/components/Authenticator.jsx, examples/solid/sign-up-in/src/ContentPage.jsx, examples/solid/uploads-list/src/components/Authenticator.jsx, examples/vanilla/sign-up-in/src/main.js, examples/vue/file-upload/src/components/Authenticator.vue, examples/vue/file-upload/vite.config.js, examples/vue/sign-up-in/src/ContentPage.vue, examples/vue/sign-up-in/vite.config.js, examples/vue/uploads-list/src/components/Authenticator.vue, examples/vue/uploads-list/vite.config.js, packages/keyring-core/src/index.ts, packages/react-keyring/src/Authenticator.tsx, packages/react-keyring/src/providers/Keyring.tsx, packages/react-keyring/test/Authenticator.spec.tsx, packages/solid-keyring/src/providers/Keyring.ts, packages/vue-keyring/src/providers/Keyring.ts
Unfortunately this also required some changes to the "keyring" interfaces - shipping another major release based on these changes is slightly annoying but probably the right thing to do, and honestly I'm probably the only person who will need to upgrade deps for now.
=> fix!: update examples for new authorize flow

examples/react/w3console/src/components/Layout.tsx, examples/react/w3console/src/components/elements.tsx, examples/react/w3console/src/pages/docs.tsx, examples/react/w3console/src/pages/index.tsx, examples/react/w3console/src/pages/terms.tsx
Refactor a bit to make it easier to wrap terms and docs in the same layout. Previously there was no link to get back to the main page from terms, which was not great.
resolves #398
=> feat: add docs page

examples/react/playground/package.json, packages/keyring-core/package.json
`test` was added to the `tsconfig.json` at some point and the types output started to include the `test` directory instead of just the contents of `src`.
=> fix: types location

examples/react/w3console/package.json, examples/react/w3console/src/components/Layout.tsx, examples/react/w3console/src/components/Uploader.tsx, examples/react/w3console/src/components/UploadsList.tsx, examples/react/w3console/src/pages/index.tsx, pnpm-lock.yaml
Plenty of polish we could still do, but this takes care of the most egregious problems on smaller screens:
https://user-images.githubusercontent.com/1113/230239853-c93deef4-f8fd-426c-8002-1a8ff192cd5c.mov
We're using HeadlessUI's Dialog and Transition components to make the small-screen sidebar feel nice.
=> feat: get w3console looking acceptable on mobile

examples/react/w3console/src/components/Uploader.tsx
we'll probably want to rework this in the future, but I think this probably looks good enough for now:
resolves #464
=> feat: add warnings about the public and permanent nature of w3up uploads

.github/actions/pnpm/action.yml, eslint.packages.js, package.json, packages/solid-keyring/src/providers/Keyring.ts, packages/vue-keyring/src/providers/Keyring.ts, packages/vue-uploader/src/providers/Uploader.ts, packages/vue-uploads-list/src/providers/UploadsList.ts, pnpm-lock.yaml
This PR fixes the compile error: `The inferred type of X cannot be named without a reference`.
I'm not sure why this is not seen in CI...
=> fix: inferred type error

docs/uploader-core.md, packages/react-uploader/src/Uploader.tsx, packages/react-uploader/src/providers/Uploader.tsx, packages/solid-uploader/src/providers/Uploader.ts, packages/uploader-core/src/index.ts, packages/vue-uploader/src/providers/Uploader.ts
This exposes the `upload-client`'s `uploadCAR` function in the `UploaderProvider`.
I need to be able to access this to upload merkle clock events generated by bucket mutations to w3up.
=> feat: implement `uploadCAR` in uploader

packages/keyring-core/package.json, pnpm-lock.yaml
@web3-storage/access-client@15.0.0 was mistakenly built with code that can use the voucher protocol. update to 15.2.0 to fix https://github.com/web3-storage/w3ui/issues/545
=> fix: bump access package to stop using voucher protocol

packages/react-keyring/package.json, packages/solid-keyring/package.json, packages/vue-keyring/package.json, pnpm-lock.yaml
this fixes an issue where we were using a broken version of access-client
=> fix: bump keyring package versions to bring in latest keyring-core

packages/react-uploader/package.json, packages/react-uploads-list/package.json, packages/solid-uploader/package.json, packages/solid-uploads-list/package.json, packages/vue-uploader/package.json, packages/vue-uploads-list/package.json, pnpm-lock.yaml
this deploys changes that fully deprecate the old voucher protocol
=> fix: set minimum workspace dep versions to bump package numbers

.github/workflows/release.yml, .github/workflows/w3console.yaml, examples/react/w3console/src/components/W3API.tsx, examples/react/w3console/src/components/services.ts
unify service configs for w3console
=> feat: use two env vars to configure service not four

packages/react-keyring/package.json, packages/react-keyring/src/index.ts, packages/react-uploader/package.json, packages/react-uploads-list/package.json, packages/solid-keyring/package.json, packages/solid-uploader/package.json, packages/solid-uploads-list/package.json, packages/vue-keyring/package.json, packages/vue-uploader/package.json, packages/vue-uploads-list/package.json, pnpm-lock.yaml
so that clients don't need to include a manual dependency on `keyring-core`
also unpin a bunch of workspace deps
=> feat: re-export Service from `react-keyring`

packages/solid-uploader/package.json, packages/solid-uploads-list/package.json, packages/vue-uploader/package.json, packages/vue-uploads-list/package.json, pnpm-lock.yaml
We made major releases of their dependencies, so we should make major releases of these so that someone installing one of them in isolation gets the latest keyring and core deps.
=> feat!: pin solid and vue upload packages

packages/core/package.json, packages/core/src/index.ts, packages/react/src/Authenticator.tsx, packages/react/src/providers/Provider.tsx, pnpm-lock.yaml
This resets the store, deleting the local agent's private keys and saved delegations. This is better than the previous implementation, and is appropriate for use cases like using console on a public or shared computer.
This PR also has a small tweak to replace JSX.Element with ReactNode, which I've found works better in downstream applications.
=> feat: add a logout function 

examples/react/components/src/Uploader.tsx, examples/react/multi-file-upload/.eslintrc.cjs, examples/react/multi-file-upload/.gitignore, examples/react/multi-file-upload/README.md, examples/react/multi-file-upload/index.html, examples/react/multi-file-upload/package.json, examples/react/multi-file-upload/postcss.config.js, examples/react/multi-file-upload/src/App.tsx, examples/react/multi-file-upload/src/index.css, examples/react/multi-file-upload/src/main.jsx, examples/react/multi-file-upload/tailwind.config.js, examples/react/multi-file-upload/vite.config.js, examples/react/uploads-list/.eslintrc.cjs, examples/react/uploads-list/.gitignore, examples/react/uploads-list/README.md, examples/react/uploads-list/index.html, examples/react/uploads-list/package.json, examples/react/uploads-list/postcss.config.js, examples/react/uploads-list/src/App.tsx, examples/react/uploads-list/src/index.css, examples/react/uploads-list/src/main.jsx, examples/react/uploads-list/tailwind.config.js, examples/react/uploads-list/vite.config.js, examples/test/playwright/src/multi-file-upload.spec.ts, examples/test/playwright/src/uploads-list.spec.ts, packages/react/src/Uploader.tsx, packages/react/test/Uploader.spec.tsx, pnpm-lock.yaml
Make backwards compatible API changes to support multi-file upload and directory wrapping.
Also support directory selection, wrapping the wonky builtin API with something a little cleaner.
Revive the multi file upload and uploads lists examples!
=> feat: support multi file upload and directory wrapping

packages/react/src/Uploader.tsx
this was preventing the checkbox state from showing correctly
=> fix: checkbox state uses `checked` not `value`

.github/workflows/release.yml
This secret doesn't have the right scopes and is preventing release-please from finding the PR, i.e. `RequestError [HttpError]: Error creating Pull Request: Resource not accessible by integration`.
=> fix: remove unneeded secret

packages/core/package.json, pnpm-lock.yaml
Upgrades `@web3-storage/upload-client` and `@web3-storage/access` to the latest versions. Causes downstream application to use the Blob protocol transparently, without affecting the API it presents.
Supersedes #633, an older version of the same upgrade.
=> feat: Use client v16.0.0 and the Blob protocol

eslint.packages.js
Otherwise it can't lint everything. This is solved with the [`projectService` option][1] in [`@typescript-eslint/parser` v8][2]. However, we're stuck firmly on v5 for now.
[1]: https://github.com/typescript-eslint/typescript-eslint/pull/8031/files?short_path=f55b3fe#diff-f55b3fe275ea73e5e0cbfaf72c238d8fa863819992fe17e23668d1f0376a18b4
[2]: https://github.com/typescript-eslint/typescript-eslint/commit/b9796c1ac49d36a9d372794371c558589c19f5a3
```sh
$ pnpm exec eslint packages/react/src/Uploader.tsx
/Users/peeja/clients/storacha/w3ui/packages/react/src/Uploader.tsx
0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/packages/react/src/Uploader.tsx` using `parserOptions.project`: /users/peeja/clients/storacha/w3ui/tsconfig.json
However, that TSConfig does not include …
```
=> chore: Point ESLint at all `tsconfig.json`s

packages/react/src/Uploader.tsx
Because we're using `createElement` from an old version of AriaKit, TS isn't checking the type of our `onSubmit` handler. It's not currently broken, but it's not being checked either. This change ensures it's correct, and makes it more correct by satisfying the types and the linter. Notably, an async function should not be a handler directly; instead, a handler should kick off an async function and attach an error handler as required. This satisfies lint rules against leaving promises dangling (apparently) accidentally.
=> refactor: `onSubmit` handler should have correct type

eslint.packages.js, examples/react/components/src/Uploader.tsx, tsconfig.json
The `Errored` component says `Check the browser console for details`, but then doesn't put the error in the console. Now it does. 😄
=> fix: Display Uploader error in console, as promised

examples/react/components/package.json, package.json, packages/core/package.json, packages/react/package.json, pnpm-lock.yaml
Use `pnpm dev` to build both packages in watch mode.
Also, upgrades `bunchee` to get past [a bug in its watch mode](https://github.com/huozhi/bunchee/issues/383). This is a big upgrade (two major versions), but everything builds fine—the upgrade doesn't appear to be as breaking as that sounds. Worth double-checking, though.
=> chore: Add `dev` script

packages/react/src/hooks.ts
The rest of https://github.com/storacha/project-tracking/issues/125. This along with [generating the space delegations on the fly during `access/claim`](https://github.com/storacha/w3up/pull/1555) will make new spaces appear on the page without logging out.
---
If the client is restored from local storage, it may be out of date. This fetches the latest delegations from the server and updates the client. This makes loading the client from local storage a stale-while-revalidate operation.
=> feat: Re-`claim` delegations during client setup

packages/core/package.json, packages/core/test/client.spec.ts, pnpm-lock.yaml
Bump `@storacha/client` version to the lastest one, so we can create spaces using the new gateway authorization flow.
=> fix: using the latest client to create spaces

packages/core/package.json, packages/react/.force-a-release, pnpm-lock.yaml
Bump `@storacha/client` version to the latest one which contains the fix for the gateway authorization flow.
=> fix(core): update storacha/client version
