storacha/w3ui

- docs/README.md
- docs/keyring-core.md
- package-lock.json
- package.json
- packages/keyring-core/LICENSE.md
- packages/keyring-core/README.md
- packages/keyring-core/package.json
- packages/keyring-core/src/index.ts
- packages/keyring-core/tsconfig.json
- release-please-config.json
- rollup.config.ts
- tsconfig.base.json
- tsconfig.json
This is a straight copy of `wallet-core`.
> feat: add keyring-core module

- examples/vue/file-upload/src/components/Authenticator.vue
- examples/vue/sign-up-in/src/ContentPage.vue
- examples/vue/uploads-list/src/ContentPage.vue
- examples/vue/uploads-list/src/components/Authenticator.vue
* make sure to loadAgent now that the package doesn't
* update uploads list for new data uploads list data format
> fix: update vue examples

- README.md
we need more in here eventually, but this gets us started
> fix: add basic documentation for storybook and w3console

- packages/keyring-core/package.json
- packages/react-keyring/package.json
- packages/solid-keyring/package.json
- packages/vue-keyring/package.json
- pnpm-lock.yaml
this integrates the fix to https://github.com/web3-storage/w3protocol/issues/344 and enables working against staging services from this library
> fix: update to latest @web3-storage/access

- README.md
> feat: update ToS link at top of README

- .github/workflows/release.yml
- examples/react/w3console/src/components/Uploader.tsx
- examples/react/w3console/src/components/UploadsList.tsx
- examples/react/w3console/src/components/services.ts
Switches the gateway host based on env var `VITE_W3UP_GATEWAY_HOST`.
> feat: switch gateway host per deployment

- packages/react-uploader/CHANGELOG.md
- packages/react-uploads-list/CHANGELOG.md
- packages/solid-uploader/CHANGELOG.md
- packages/solid-uploads-list/CHANGELOG.md
- packages/vue-uploader/CHANGELOG.md
- packages/vue-uploads-list/CHANGELOG.md
- release-please-config.json
unpin package numbers and get rid of extra CHANGELOG noise
> chore: release please cleanup

- examples/react/w3console/src/brand.tsx
- examples/react/w3console/src/components/Authenticator.tsx
- examples/react/w3console/src/pages/index.tsx
- examples/react/w3console/src/pages/terms.tsx
worked with @dchoi27 to get ToS and other legal copy on the auth page and sidebar and to make some updates to the ToS for readability and better UX
closes #397
> feat: updates to ToS and login page

- examples/react/w3console/src/components/Authenticator.tsx
it was white so it looked broken
> fix: make auth email input text black

- examples/react/w3console/src/pages/docs.tsx
pushing this mostly to trigger a new production build, but I think it's better to be consistent here
> fix: the tiniest of language tweaks!

- examples/react/playground/package.json
- packages/keyring-core/src/index.ts
Literally the string '{string}@{string}' 🙈
> fix: email type

- packages/react-keyring/src/providers/Keyring.tsx
- packages/solid-keyring/src/providers/Keyring.ts
- packages/vue-keyring/src/providers/Keyring.ts
> fix: more email type

- examples/react/w3console/src/pages/index.tsx
this gives us a soft restriction on the number of spaces a user can create - we'll enforce this server-side in https://github.com/web3-storage/w3up/issues/704
> feat: remove space creator from sidebar

- .github/workflows/release.yml
- .github/workflows/w3console.yaml
- examples/react/w3console/src/components/services.ts
- examples/vanilla/sign-up-in/src/staging-service.js
now that we've migrated to using a single service, update the w3console configs to point at it
> fix: use unified endpoint for staging services

- examples/react/w3console/src/components/Layout.tsx
- packages/react-keyring/src/providers/Keyring.tsx
> fix: correctly clear local storage

- packages/core/package.json
- pnpm-lock.yaml
Motivation:
* explicitly opt in to https://github.com/web3-storage/w3up/releases/tag/upload-client-v12.3.2 (i think it will https://github.com/web3-storage/w3ui/pull/606/commits/129f74d1a7db388dad8660b29e34b8fc4fc5ab50#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR3615)
> fix: package.json explicitly wants w3up-client@11.2.1

- packages/react/package.json
- pnpm-lock.yaml
with the version bump this is causing builds to fail
> fix: unpin core version

- packages/core/package.json
- pnpm-lock.yaml
bring in fix for `fetch.node` issue
> fix: upgrade upload client

- eslint.packages.js
- packages/react/src/Uploader.tsx
- packages/react/test/Uploader.spec.tsx
w3up-client has a `Client#uploadCAR` function - add support for this to the `Uploader`
> feat: support CAR uploads

- packages/core/package.json
- pnpm-lock.yaml
bring in new `plan/set` invocation API from `w3up-client` and `access`
> feat: upgrade `core` dependencies for `plan/set`

- packages/react/src/Uploader.tsx
- added to a comment to trigger a release
> chore: migrate repo

- packages/react/src/Uploader.tsx
it looks like I wrote the wrong PR title last time, so let's try again.
- added to a comment to trigger a release
> fix: migrate repo

- .github/workflows/release.yml
With the new read defaults these were missing!
> fix: add missing permissions to the release pipeline

- packages/core/package.json
- pnpm-lock.yaml
Version 16.2.0 of w3up-client allows Space Sharing via e-mail - which will be useful for the Console App.
> chore(core): bump w3up client version

- .github/actions/pnpm/action.yml
- package.json
[As in `console`.](https://github.com/storacha-network/console/pull/117)
> chore: Add packageManager to package.json

- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/service.ts
- pnpm-lock.yaml
This should fix uploads in non-prod environments (a fix which was applied in the new client, but not the old one).
> feat: Use latest client (`@storacha/client`)

- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/service.ts
- packages/react/.force-a-release
- pnpm-lock.yaml
- Revert to `web3-storage/w3up-client` in `core` package.
- Update code references.
> fix(core): revert to web3-storage/w3up-client
